# Makefile

all: execing execing2

execing: execing.c
	gcc -o execing -std=c99 -Wall -O1 execing.c

execing2: execing2.c
	gcc -o execing2 -std=c99 -Wall -O1 execing2.c

clean:
	rm -f execing
	rm -f execing2
